maze1:
- '11111111111111111111111111111111111111111111111111'
- 1S000101000000010010111100011000101110001010101111
- '11011001101100011100000110101110100000111001001011'
- '10010101110100000000100100100010110011101011010101'
- '10100001000111000110010100000101010011011001010011'
- '10000100000000001001010100111010011110011000101011'
- '11101001111010101010010011000111000110010000111101'
- '11100110010110111101011001110001101100110010101001'
- '11111001011101111011101111110100101010111010000001'
- '10000000111101111011001110001010111111110111000001'
- '11000110111101111010111100101000011110011011011101'
- '10010001101110111100101101110010101010010010111101'
- '10001110010110010001101001100000010100001000000111'
- '10111011101100000010100110000100001010111000000011'
- '11010000001010011111011110111100011100011111111011'
- '10000100100000110110111101100101010011001001110111'
- '10100000010000000010010001100110100100010010101111'
- '10111011110000100010111011101111101001111101110111'
- 1011011010100100000110011110111010101000F010110101
- '11111111111111111111111111111111111111111111111111'
maze2:
- '11111111111111111111111111111111111111111111111111'
- 1S001111101001010101010100001011010000110110000011
- '11011001010010100001110110111111101100000110111111'
- '10000110000100101110101010100000111100001101111111'
- '11111101101101111000001010011111000000000100100001'
- '11000001001101101010000100111010000011001010000011'
- '11000011000000010100000011100101001110100100000101'
- '10001101000001001011000100101111001011101100111101'
- '10100101011110001110000000000010011101010110010011'
- '11011111000001101101001001100000000101000010110001'
- '11000100101010110010111100000101000010001001000111'
- '11111101001101101111011001100111011100101101101111'
- '11001100000100000000110101110110111100000011101101'
- '10011011001010101010010111001110011100010101011011'
- '10011110111110100000111000010110000000101010100011'
- '10010111011111111110100000010000111000010101001011'
- '10110010101010001110100100011011111111111100000011'
- '11000001111111010111101100011000111000001110001101'
- 1100111100010111011010101011010000011100F001001011
- '11111111111111111111111111111111111111111111111111'
mazebfs:
- '11111111111111111111111111111111111111111111111111'
- 1S001110001010011000000000000110000000000100110001
- '10101000001010000000101010011000000000011000011001'
- '10011000001010110110101100000110000000000010001001'
- '11001010001010001111000100000100000011010100010001'
- '10001100100000010001000000001010001000100000100101'
- '11001100010101000010110010100011101100000110000001'
- '11001000000101000010000100000000001010000100101001'
- '11001010000001000001000001011000100000001000010001'
- '11101100100001001100101000001000011100110000010011'
- '10101000101011100010010001101000000100100100000101'
- '11101010011101101001110110001010010101000101000011'
- '11001011001101110101101100010000011011110010011001'
- '10101001000101010010001000000001100110000000100101'
- '10001000100001001110010000100000000000100111000001'
- '11011010000001001011101010000110010100001000100011'
- '10000001000101100010000000000000100010100101000011'
- '10010010000101001000101000000010000010001001000001'
- 1000010011010010010000001000010110000000F010101001
- '11111111111111111111111111111111111111111111111111'
100maze:
- '1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'
- 1S00001000000000101100010010000000100100000010000001000010010110000100000000011010100100000001110001
- '1101101110110100000000001010100011000000010010000000000000000110000100000101000000011000001000000011'
- '1100000010111000000001001000011110000100001001001100100001001011011101000010110001000011100000010101'
- '1110011011010000000000001000001010000000100000111000000000101011001000010010001000100100100001000011'
- '1001110000000000100000100100000000100000010000001000001000101100001110001100010000000101000101100001'
- '1000001101110000101010010100001101001001100010110000101000110100001000010000000100000000010000010001'
- '1010000010110100011110000100110000000100000011110001010000010001000100000010010100000100010010110101'
- '1100010011000000001000111010000010100100010010000000000000001111010001001010110010000001001101000001'
- '1100010001100011110000100000010001100000000010010110110111000101000101000001010001000101001110000001'
- '1110000000100100101011010110100000000001000011101010000010010000000010000011000010000011011100001001'
- '1010110100001000001100010110100001011001100100001010111110000000100000010000000010111100100000111101'
- '1001010110000010000011001110010011001001111000000100001000000011011000000010100010110000101010100011'
- '1100001010000001000110111010001010001001000101111110000001000001001100000100001110100010000010001111'
- '1101110100001000000010000100100000000001000000001000001110110000000100000001010001100001010001111111'
- '1001000000000010000000001000011100011000100000110001001000001000011100101010011010110101000011000001'
- '1000001000010000000100000010000110000000100000001011101110010000000000100010110001100011001111001001'
- '1111000100100000000110000000000010000010101001000001001010100001001110011001000111010110010110011011'
- '1010110100000000010000100101100010000000100010000110111001100100001000100000001001001100001100011101'
- '1010001000100000100011001000000000000100000001010111100001000000011000011110001011000100110101001001'
- '1010000110000011000100001010010010000111000100010010101010100010011110000101011001000000010000100001'
- '1000000011100000101110010011000000000000010000001001001100100000000010000011100011000100100000001101'
- '1000010010111001000011110010100000000011000000000110000011000000101010001000100000100100000111001001'
- '1101011000010001000100000000100110010001000101111000100000000111011000111100000010000000010100000001'
- '1000000001000011011000000000000011000001011001011000011111001010010001001101011110100000000010001001'
- '1011001101110000000011001110011001001000100101011001001010000100000000100010100100100000010001001001'
- '1111000010000011101100000000100011111001010100111000001001110100001000100001000101000111100001100001'
- '1000100000100100100110001010100000100011100010000111000100000000010010110110000010000100010010000101'
- '1101100101001000011010000100100010000010001010000000010000000000010101000010110101001110011001101011'
- '1000001001110110000100110010001000000001000001000011000010010000010000000010000101000101001010000001'
- '1000000010100000010000001110001000010101000000000001101000110110101011011011100001010000010010001001'
- '1001100101000000001000110000000000010000001110011000101010100110000110000000010100110010010100000011'
- '1101000110001101100100100010001100100010100100000010000001100010001000000001100101101011000001011001'
- '1001111000001000100101000010000000011111000010000000100100111101101001010100010110001101010000000101'
- '1111010011110000100001100000000001000011000110100010000010000101001000100010011001100101101000000001'
- '1000000101000000100000010101000111110000000100010000110011110100111100010000100000000100111001110111'
- '1000101000010010111000000000100110000000101110000000100000000111000001000000001100000100000000000001'
- '1000101100101000100100110000001011101000000100101100011101001000111100000000000100001100001000101001'
- '1010000000010010011100110001001000000000000001000110100001100001000000011100100000010010000101110111'
- '1010110100000011000011000110100000011000000001100010100000000001000000000011000100101010110001001001'
- '1011000001000110001000000101010101000000110101000000000110010100011000000010111000100100100100110001'
- '1110110000010110100010000011001101110101010100000000000010001000001110101010110001100000000001100001'
- '1000000100000100000001010001000001011010000001000100100001010010001010001101011111001001010111001101'
- '1001101010000000110001010010001011000000000100000000110011001010000000010010000011000111001101001001'
- '1110010011011010010000010010111010011000010010011000010110000001000001001001000000101000001000000001'
- '1011010000111100101101000010100000100010010000001001000000000010001000000010010100011000000100110101'
- '1000001001100001000010001010000000001001000001000000000111110000100000100000001000100010001001100111'
- '1000000000000110100011000010101000000000010110010000000000000000000011100001001000000001101000011011'
- '1101001000100001011100011010000110000111001101000100000101001000010101011001000111100000100000000001'
- '1000000110000010100000000000000100010010100110100101000000010000000001110000010000001110101000000101'
- '1011000000000000001101110000011100000000000000000010010000010000010001010100001110010000000000000001'
- '1001000110111000001101001001101001010100000100011110111001000001101000001010100100001110110100010001'
- '1011000100011111000100000100001100010101000010000000001010000000000010011111100100000100100000000011'
- '1100011001100000010101011010101001000100010100000000000001000010100110010111011110000101100100101011'
- '1100010010101111011100000000110110010100111101000011011001000000010100000001100010011101011010111011'
- '1101110001001110010000011110000001000000100011110000000101000101000100000000100100100100000000000001'
- '1100010100110010001000100001100000000101001000110010010100010000000101000110001000001101000011000011'
- '1000000010011000111000000110000110010000110110000110100010000100010111010101000011000101000010101111'
- '1000010011100110000000011000000000001001100001001000000000000001010001101111000000000001001010000001'
- '1110000000010110010100000000000000010010000010000000101000010011000000000101000100000100001000110001'
- '1111000000000100010100111001010001100100000010000010010000000000000000000110000111010000100000001001'
- '1010010000000000000000110000110000000000110010010101101100001101011001000010010001100000000011000011'
- '1100001010110101000001001110011000000000000000000011000000100001000000010100001010010110101100001111'
- '1000000101100001110000100001001001000001000110100001101011000000111010100011010000000001011000100111'
- '1000000000000010010101101000101010010110000010000000010000000000010010011010000001010000100011000011'
- '1000100110100110000010001110001000000100000010101010110111100101011000011100100001000000000001111011'
- '1001000000000011010010110000101010010000011010000000000001010100000011111000101100000000000110000101'
- '1010000010011000100000100011000111100100010110110000000010101110000101000000111011101111110000000111'
- '1000000010010000001000011000011000111001101001100100101000000101101001001100000010100000001001000101'
- '1100100000100100110001101001100001000000011000111110000000011000010000100001100011000000100010101111'
- '1101001000110000001000000000000010111110000001000000010101000000100001000101010000001000011100000011'
- '1001011001000110100000010100000100010100110000000001000010000001000000110000000001000000000000101001'
- '1010001000001101000000010000000000001011111000000010100100000000000000001011000010000001001000000001'
- '1100010000000000100000001000100000110000011000000101100000101111000000110111000010001001111010010101'
- '1011001010110000000000010000111000110011110010000110010000000000111000000100011000010001010010000001'
- '1010000000000000100000101000010010100000010011001000110001101010000000010010010110111000100110011001'
- '1100000010000110010000100011000010100010000000011000001110000000000011010100110101100001001000000011'
- '1101000000100110001100100101000000001010000100001010010001101000100100001000100110101101111110111001'
- '1011000110000110000000101000000010001000111000010101100110011100100001000000001000110001010110000001'
- '1001110100000001110001010100101000010000000001100001000011001010000010001110001110000011100101110001'
- '1001000000110000000000000010100010000001000100000000100000010001000100000101000010010110000000001001'
- '1000010011111000010100011010100110100010110001001101010000000000011011101001010000000010000111000001'
- '1000010000000100001000000010100000100000001001001000001110000010001001000001100111100000000000010001'
- '1010100011100000001010000000111100000001001110001010100001010000100000001000010100001001100111101101'
- '1010000100010100110101110000001100001100101010000000101000110001100000100110010111001010100000001001'
- '1001001111011110001000100110000011100000000000001001001001100000110000000000100100000000001001000011'
- '1100000000010000010001111000100001100000100000101010110000001010011100000110010011010110000010101111'
- '1010000001000010100000000100000000010011010000100000000010100010000101000001100001010001100101010101'
- '1000001010000010000011100000101100000000000100110000001000010000000001100110111001110001011000000001'
- '1101000010010001001000011111000000000000110000000010000100000100110000010010110000001000000001011011'
- '1100110100100001100100000100100000001110000100000001000000100001000010000010001100000110000001010101'
- '1100011000000010000000010010110100000010000000001010010010000101010001000000110001110100111011001001'
- '1000001000010010001000100010011010010101011110110001100110100110100000010001111110100001000011001101'
- '1100010100110000000010010010010110000001100000111001000010111111010000100000100100011010000001000001'
- '1001010001000000000100001001001110001010100010000000001110010000100010000000101100010001000001110101'
- '1000000100001110100010000011100001000000000010000000000110110000010001100001000101011001101000001001'
- '1000001110001100101010001010100111010010000001000001011000000010000101010000000100000000101000000111'
- '1000111000001111000011110001101010011100100000000000000100100110000010011000011010100111010100000011'
- 10011000100000110100000001000001100000101000010100110000100100001000110011010010001010010000010110F1
- '1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111'
maze3:
- '111111111111111111111111111111'
- 1S1010110001001100110100100011
- '100100010000010100100100000101'
- '100010000001010010001000010011'
- '111001000010001100100100111011'
- '100000000010100111000010101101'
- '110001000000010000110000000001'
- '110001010100000100000010000001'
- '100000010000000001001000010101'
- '100000000110110101000110111001'
- '100000111000010100000010000011'
- '100000111100001001100010101011'
- '101011100100001110011000110001'
- '101010101001101100010111001001'
- '100100001010000000001001010011'
- '110010000000100011010100100011'
- '100000010000000101001100100001'
- '110001000010010011001010001001'
- '110000100101000001010100001001'
- '110000000110101001110001100101'
- '100111000000010001100100100001'
- '110100110001000010001001001101'
- '110101010000100011000001000001'
- '101001000001110010111000010011'
- '100000000011000000100000000001'
- '100000000001000001110001000011'
- '100000000000110011010001101101'
- '111000110110101100110100000001'
- 1000010101110010000101000110F1
- '101100111101011101000001001101'
- '100000001111001111001000000101'
- '100011010010000101000100000101'
- '110110010100000000001010010101'
- '110101000110001111000000010011'
- '110001001001011100000100000111'
- '100110100000001010000100000001'
- '100000100000000101011101100001'
- '111001010010101111101001000011'
- '100000000110001100000000000001'
- '111111111111111111111111111111'
maze_test:
- '11111111111111111111111111111111111111111111111111'
- '11000010101110000110010101110010111111001111010111'
- '10111011011000011011100001100001110101001010100011'
- '11011010100100101000010101100001111000111010010111'
- '10101101111111000101110001110001010101010101100001'
- '11010010101110011001100001010110111111010110111011'
- '10010111110001011100001111001010100001110000111011'
- 1001S000110111111000111001011000100001100000001101
- '11101100010101001010000101100000010101110101111101'
- '10001101011000011100111110010010111100110110000001'
- '10101111010101010101101111001001110100111001100111'
- '10010010111000101111000001110110100011011110111001'
- '10101000101001110010101011001011110010001110110001'
- '10110001011111000101101101001011000010100000011111'
- '10011000011001110010110100011001101010111100111111'
- '11001000010011010110000100110110000010110000111011'
- '10100000101111100101110100101110110101111010111011'
- '10111011100010101110001100001100111111111000011111'
- '10101111101010000011000101001010001111001000111011'
- '10000011011100011100111100101000101110101000110011'
- '11001000101011001111110100100111110110110001010111'
- '11000011010100000000110100111100001110100110101011'
- '11100010011000100011000010101001111111000100000111'
- '11000010001101001010010111101010100010100001000101'
- '10011010100010011000111101101111110001100001011011'
- '10010101001010110111000001100111011011000000111001'
- '11000111000111100100110001110011000000100011001001'
- '11011000011010101011001011011111011111011000100111'
- '11000110111001001111001001001011011011010011101001'
- '11111110111000010000100010000111011100110110011111'
- '11010101110101011110000000001111101110110101001011'
- '11010110110111000001110100100001110100110010010011'
- '10001111011001000011110111110001110100010101100101'
- '11001110101001010000011001011010010010111110111101'
- '10101110111101001110000001111100010100001000001001'
- '10010111001101101001011110011101011111010100001001'
- '10101000010010000110010010001011101010010010001001'
- '11111110011110000011011001100110100110001000100001'
- '11011000011110000010000101111000011100010001011111'
- '11111000111101010001011111111000111011100110011001'
- '10010011100110101000101001100100110111110110111001'
- '11101000001110011111001110011011111101010100110111'
- '11100001000001011100111001111001001100000111100011'
- '11010001110100100100111000000100011110001000001111'
- '10010011011101000010010101110000001100111101111111'
- '11010110100110011110001001010101001010111101100101'
- '11000111100110010000100011000101111000110011011101'
- '11011010110110010111010101111101000100110011100011'
- 1000110101111101010001110010100100010100F001101001
- '11111111111111111111111111111111111111111111111111'
