maze1:
- '11111111111111111111111111111111111111111111111111'
- 1S000101000000010010111100011000101110001010101111
- '11011001101100011100000110101110100000111001001011'
- '10010101110100000000100100100010110011101011010101'
- '10100001000111000110010100000101010011011001010011'
- '10000100000000001001010100111010011110011000101011'
- '11101001111010101010010011000111000110010000111101'
- '11100110010110111101011001110001101100110010101001'
- '11111001011101111011101111110100101010111010000001'
- '10000000111101111011001110001010111111110111000001'
- '11000110111101111010111100101000011110011011011101'
- '10010001101110111100101101110010101010010010111101'
- '10001110010110010001101001100000010100001000000111'
- '10111011101100000010100110000100001010111000000011'
- '11010000001010011111011110111100011100011111111011'
- '10000100100000110110111101100101010011001001110111'
- '10100000010000000010010001100110100100010010101111'
- '10111011110000100010111011101111101001111101110111'
- 1011011010100100000110011110111010101000F010110101
- '11111111111111111111111111111111111111111111111111'
